name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Test
        run: |
          xcodebuild test \
            -project DummyCIApp.xcodeproj \
            -scheme DummyCIApp \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
